DROP TABLE IF EXISTS stats CASCADE;

CREATE TABLE IF NOT EXISTS stats(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(100),
    uri varchar(100) NOT NULL,
    ip varchar(100) NOT NULL,
    hit_time timestamp);